def generate(n):# n is the number of digits
    if n == 0:#base case
        return ['']#returning an empty list if n is 0
    elif n == 1:#base case
        return ['0', '1']#returning a list containing 0 and 1 if n is 1
    else:
        L = []#creating an empty list
        for i in generate(n - 1):#iterating through the list generated by the function
            L.append('0' + i)#appending 0 to the beginning of each element in the list
        for i in generate(n - 1):#iterating through the list generated by the function
            L.append('1' + i)#appending 1 to the beginning of each element in the list
        return L#returning the list

print(generate(40))

#generate n digit hexadecimal numbers
def generate_hex(n):
    if n == 0:#base case
        return ['']#returning an empty list if n is 0
    elif n == 1:#base case
        return ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F']#returning a list containing 0 to F if n is 1
    else:
        L = []#creating an empty list
        for i in generate_hex(n - 1):#iterating through the list generated by the function
            for j in generate_hex(1):#iterating through the list generated by the function
                L.append(j + i)#appending j to the beginning of each element in the list
        return L#returning the list
